spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:10002
      eager: true
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  application:
    name: Sentinel-Nacos-Demo
project:
  name: Sentinel-Nacos-Demo